name: Test

on: [push]

jobs:
  dev-build:
    name: 'dev-build'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Packages
        run: npm i
      - name: Build library
        run: npm run dev:build
  
  run-tests:
    name: 'run-tests'
    needs: dev-build
    runs-on: ubuntu-latest
    steps:
      - name: Install Packages
        run: npm i
      - name: Build tests
        run: npm run test:build
      - name: Run tests
        run: npm run test:run
        continue-on-error: false
